org: jogeshgupta963
app: auction-service
service: auction-service
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    region: us-east-1
    stage: ${opt:stage,'dev'}
    iamRoleStatements:
        - ${file(iam/AuctionsTableIam.yml):AuctionsTableIAM}
    environment:
        AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
resources:
    Resources:
        AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
functions:
    createAuction:
        handler: src/handlers/createAuction.handler
        events:
            - httpApi:
                  path: /auction
                  method: POST
    getAuctions:
        handler: src/handlers/getAuctions.handler
        events:
            - httpApi:
                  path: /auction
                  method: GET
    getAuction:
        handler: src/handlers/getAuction.handler
        events:
            - httpApi:
                  path: /auction/{id}
                  method: GET
    placeBid:
        handler: src/handlers/placeBid.handler
        events:
            - httpApi:
                  path: /auction/{id}/bid
                  method: PUT

    processAuctions:
        handler: src/handlers/processAuctions.handler
        # events:
        #     - schedule: rate(1 minute)

custom:
    AuctionsTable:
        name: !Ref AuctionsTable
        arn: !GetAtt AuctionsTable.Arn
