org: jogeshgupta963
app: auction-service
service: auction-service
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    region: us-east-1
    stage: ${opt:stage,'dev'}
    iamRoleStatements:
        - ${file(iam/AuctionsTableIam.yml):AuctionsTableIAM}
        - ${file(iam/MailQueueIam.yml):MailQueueIAM}
    environment:
        AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
        MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    httpApi:
        authorizers:
            customAuthorizer:
                type: request
                functionArn: ${self:custom.authorizer}
resources:
    Resources:
        AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:
    createAuction:
        handler: src/handlers/createAuction.handler
        events:
            - httpApi:
                  path: /auction
                  method: POST
                  authorizer:
                      name: customAuthorizer

    getAuctions:
        handler: src/handlers/getAuctions.handler
        events:
            - httpApi:
                  path: /auction
                  method: GET
                  authorizer:
                      name: customAuthorizer

    getAuction:
        handler: src/handlers/getAuction.handler
        events:
            - httpApi:
                  path: /auction/{id}
                  method: GET
                  authorizer:
                      name: customAuthorizer
    placeBid:
        handler: src/handlers/placeBid.handler
        events:
            - httpApi:
                  path: /auction/{id}/bid
                  method: PUT
                  authorizer:
                      name: customAuthorizer

    processAuctions:
        handler: src/handlers/processAuctions.handler
        # events:
        #     - schedule: rate(1 minute)

custom:
    authorizer: arn:aws:lambda:us-east-1:747441403622:function:auth-service-dev-auth
    AuctionsTable:
        name: !Ref AuctionsTable
        arn: !GetAtt AuctionsTable.Arn
    MailQueue:
        arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
        url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}
